{% set name = "posix_ipc" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/posix_ipc-{{ version }}.tar.gz
  sha256: b21b8c7f39ad26b5fb21d84c3e3a31426eb68c43bc5a23e3cd6815488c668a05

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - posix_ipc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/osvenskan/posix_ipc
  summary: POSIX IPC primitives (semaphores, shared memory and message queues) for Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
